spring:
  main:
    web-application-type: none

# 小智聊天服务配置
chat:
  server:
    port: ${CHAT_SERVER_PORT:8082}
    context-path: /clda/v1
  client:
    apiKey: ${CHAT_CLIENT_APIKEY:}
    url: ${CHAT_CLIENT_URL:https://open.bigmodel.cn/api/paas}
    model: ${CHAT_CLIENT_MODEL:glm-4-flash}
    path: ${CHAT_CLIENT_PATH:/v4/chat/completions}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    org.springframework.ai.tool: ${CHAT_LOG_LEVEL:DEBUG}

# 模型配置
model:
  asr:
    sense-voice:
      model-dir: ${MODEL_ASR_SENSE_VOICE_MODEL_DIR:./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17}
      num-threads: ${MODEL_ASR_NUM_THREADS:4}
  tts:
    volc-tts:
      appid: ${VOLC_TTS_APPID:}
      access-token: ${VOLC_TTS_TOKEN:}
